services:
  vote:
      build:
        context: ./vote
        dockerfile: Dockerfile
      restart: on-failure:3		
      ports:
        - "8080:8080"
      depends_on:
        - redis
      healthcheck:
          test: wget --no-verbose --tries=1 --spider http://doryanpl.fr:8080 || exit 1
          interval: 60s
          retries: 5
          start_period: 20s
          timeout: 10s

  redis:
      image: "redis:7.2.3-alpine"
      volumes:
        - redis-data:/data
      restart: on-failure:3	
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 10s
        retries: 3
      
  worker:
      build:
        context: ./worker
        dockerfile: Dockerfile
      restart: on-failure:3	
      depends_on:
        - redis
        - postgres

  result:
      build:
        context: ./result
        dockerfile: Dockerfile
      restart: on-failure:3	
      ports:
        - "8081:8081"
      depends_on:
        - postgres
      healthcheck:
          test: wget --no-verbose --tries=1 --spider http://doryanpl.fr:8081 || exit 1
          interval: 60s
          retries: 5
          start_period: 20s
          timeout: 10s


  postgres:
      image: postgres:14-alpine
      volumes: 
        - postgres-data:/var/lib/postgresql/data
      restart: on-failure:3	
      env_file:
        - .env
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 10s
        retries: 3

volumes:
  redis-data:
  postgres-data:

      
